version: '3.7'

services:
  frontend-react:
    container_name: frontend_CICD_container
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    volumes:
      - ./frontend/src:/usr/src/app/src

