name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Send Approval Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "🚀 Deployment Approval Needed"
          body: "Code has been pushed/merged to main. Please approve deployment to EC2 by visiting the GitHub Actions page and clicking 'Approve'."
          to: ${{ secrets.APPROVER_EMAIL }}
          from: GitHub Actions <${{ secrets.MAIL_USERNAME }}>

      - name: Wait for Manual Approval
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Manual approval step
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: ${{ secrets.APPROVERS }}
          minimum-approvals: 1
          issue-title: "Deployment Approval Needed"
          issue-body: "Please approve this deployment to EC2."

      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git fetch
            git pull origin main
            docker compose up -d --build
